// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Shravanth. All rights reserved.

package service

import (
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// ExportFormat defines the output format for export.
type ExportFormat string

const (
	FormatEnv  ExportFormat = "env"
	FormatJSON ExportFormat = "json"
	FormatYAML ExportFormat = "yaml"
)

// ExportOptions configures export behavior.
type ExportOptions struct {
	Format  ExportFormat
	Filter  string
	Exclude string
}

// Export writes secrets in the specified format to the writer.
func Export(w io.Writer, secrets map[string][]byte, envName string, opts *ExportOptions) error {
	filtered := filterSecrets(secrets, opts.Filter, opts.Exclude)

	switch opts.Format {
	case FormatJSON:
		return exportJSON(w, filtered)
	case FormatYAML:
		return exportYAML(w, filtered)
	default:
		return exportEnv(w, filtered, envName)
	}
}

func exportEnv(w io.Writer, secrets map[string]string, envName string) error {
	fmt.Fprintf(w, "# Generated by Vaultless on %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(w, "# Environment: %s\n", envName)
	fmt.Fprintln(w, "# DO NOT commit this file to version control")
	fmt.Fprintln(w)

	keys := sortedKeys(secrets)
	for _, k := range keys {
		v := secrets[k]
		if strings.ContainsAny(v, " \t\n\"'#") {
			fmt.Fprintf(w, "%s=%q\n", k, v)
		} else {
			fmt.Fprintf(w, "%s=%s\n", k, v)
		}
	}
	return nil
}

func exportJSON(w io.Writer, secrets map[string]string) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(secrets)
}

func exportYAML(w io.Writer, secrets map[string]string) error {
	enc := yaml.NewEncoder(w)
	defer enc.Close()
	return enc.Encode(secrets)
}

func filterSecrets(secrets map[string][]byte, filter, exclude string) map[string]string {
	result := make(map[string]string, len(secrets))
	for k, v := range secrets {
		if filter != "" {
			matched, _ := filepath.Match(filter, k)
			if !matched {
				continue
			}
		}
		if exclude != "" {
			matched, _ := filepath.Match(exclude, k)
			if matched {
				continue
			}
		}
		result[k] = string(v)
	}
	return result
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
